provider = "openrouter"
model = "openrouter/free"
tools = []
interfaces = ["cli"]
logging = true

[memory]
max_messages = 0

# [audio]
# provider = "whisper"  # or http://localhost:9000/v1 for local whisper server
# model = "whisper-1"
