[agent]
provider = "openrouter"
model = "openrouter/free"
tools = []
logging = true  # false | true | "debug"

[access]
allow_by_default = true
interfaces = ["cli"]

[memory]
max_messages = 0

# [audio]
# provider = "whisper"  # or http://localhost:9000/v1 for local whisper server
# model = "whisper-1"
